"""Speculative Decoding Verification Routine for PagedServe.

Provides standalone Target-Draft verification logic with greedy and temperature-based rejection sampling.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class SpeculativeResult:
    """Artifact holding speculative decoding verification results."""
    accepted_tokens: list[int]
    num_drafted: int
    num_accepted: int
    acceptance_rate: float


class SpeculativeEngine:
    """Speculative Token Generation and Rejection Sampling Engine."""

    def __init__(self, num_speculative_tokens: int = 4):
        self.num_speculative_tokens = num_speculative_tokens

    def verify_and_sample(
        self,
        draft_tokens: list[int],
        draft_probs: list[list[float]],
        target_probs: list[list[float]],
        temperature: float = 1.0,
    ) -> SpeculativeResult:
        """Verifies draft tokens against target distribution using rejection sampling.

        Args:
            draft_tokens: Sequence of candidate tokens generated by draft model.
            draft_probs: Probability distribution over vocab for each draft step.
            target_probs: Probability distribution over vocab from target model for each step.
            temperature: Sampling temperature (0.0 for greedy decoding).

        Returns:
            SpeculativeResult containing accepted tokens, stats, and acceptance rate.
        """
        accepted: list[int] = []
        import random

        for i, (draft_token, p_d_dist, p_t_dist) in enumerate(
            zip(draft_tokens, draft_probs, target_probs)
        ):
            p_d = p_d_dist[draft_token]
            p_t = p_t_dist[draft_token]

            if temperature <= 0.0:
                target_token = max(range(len(p_t_dist)), key=lambda idx: p_t_dist[idx])
                if target_token == draft_token:
                    accepted.append(draft_token)
                else:
                    accepted.append(target_token)
                    break
            else:
                prob_accept = min(1.0, p_t / max(p_d, 1e-12))
                if random.random() < prob_accept:
                    accepted.append(draft_token)
                else:
                    # Rejection sampling: sample from normalized max(0, p_target - p_draft)
                    diff = [max(0.0, pt - pd) for pt, pd in zip(p_t_dist, p_d_dist)]
                    sum_diff = sum(diff)
                    if sum_diff > 0:
                        norm_diff = [d / sum_diff for d in diff]
                        r = random.random()
                        acc_p = 0.0
                        resampled = len(norm_diff) - 1
                        for idx, p in enumerate(norm_diff):
                            acc_p += p
                            if r <= acc_p:
                                resampled = idx
                                break
                        accepted.append(resampled)
                    else:
                        resampled = max(range(len(p_t_dist)), key=lambda idx: p_t_dist[idx])
                        accepted.append(resampled)
                    break

        # If all draft tokens accepted, sample 1 bonus token from final target distribution
        if len(accepted) == len(draft_tokens) and len(target_probs) > len(draft_tokens):
            final_p = target_probs[-1]
            if temperature <= 0.0:
                bonus = max(range(len(final_p)), key=lambda idx: final_p[idx])
            else:
                r = random.random()
                acc_p = 0.0
                bonus = len(final_p) - 1
                for idx, p in enumerate(final_p):
                    acc_p += p
                    if r <= acc_p:
                        bonus = idx
                        break
            accepted.append(bonus)

        num_drafted = len(draft_tokens)
        num_accepted = len([t for t, d in zip(accepted, draft_tokens) if t == d])
        rate = num_accepted / max(num_drafted, 1)

        return SpeculativeResult(
            accepted_tokens=accepted,
            num_drafted=num_drafted,
            num_accepted=num_accepted,
            acceptance_rate=rate,
        )
